import { db } from "@/db";
import { emails } from "@/db/schema";
import { cosineDistance, desc, eq, sql } from "drizzle-orm";
// Example vector search leveraging Drizzle ORM and Neon's native pgvector integration.

export async function generateEmbedding(text: string): Promise<number[]> {
  // Usually embeddings are still generated by OpenAI or Nomic since Groq focuses on chat inference.
  // We'll stick to a cheap embedding provider API here (e.g., OpenAI text-embedding-3-small).
  if (!process.env.OPENAI_API_KEY) {
    console.warn("OPENAI_API_KEY is missing! Generating a fallback 1536-dimensional array to preserve demo integrity.");
    return new Array(1536).fill(0.01);
  }
  const res = await fetch("https://api.openai.com/v1/embeddings", {
    method: "POST",
    headers: {
       "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`,
       "Content-Type": "application/json"
    },
    body: JSON.stringify({
       model: "text-embedding-3-small",
       input: text,
    })
  });
  const data = await res.json();
  return data.data[0].embedding;
}

export async function searchSimilarEmails(query: string, userId: string, limit = 5) {
  try {
    const embedding = await generateEmbedding(query);
    
    // Drizzle pgvector cosine distance search
    const similarity = sql<number>`1 - (${cosineDistance(emails.embedding, embedding)})`;
    
    const results = await db
      .select({
        id: emails.id,
        subject: emails.subject,
        snippet: emails.snippet,
        fromAddress: emails.fromAddress,
        date: emails.date,
        similarity
      })
      .from(emails)
      .where(eq(emails.userId, userId))
      .orderBy(desc(similarity))
      .limit(limit);

    return results;
  } catch (error) {
    console.error("Vector search failed:", error);
    return [];
  }
}
